# NumPy

In [15]:
import numpy as np

### Array unidimensional

In [19]:
arr_1 = np.array([1, 11, 111, 1111])
print(type(arr_1))

<class 'numpy.ndarray'>


In [20]:
# Con shape podemos ver la forma del array.
print(arr_1)
print(arr_1.shape)
print(type(arr_1.shape))

[   1   11  111 1111]
(4,)
<class 'tuple'>


### Array de dos dimensiones (m x n)

$ M^{m \times n} =
\left( \begin{array}{cccc}
 11_{0,0} & 12_{0,1} & 13_{0,2} \\
 21_{1,0} & 22_{1,1} & 23_{1,2} \\
 31_{2,0} & 32_{2,1} & 33_{2,2} \\
\end{array} \right)$

In [29]:
arr_2 = np.array([[10, 11, 12], [20, 21, 22], [30, 31, 32]])
print(arr_2)
print(arr_2.shape)

[[10 11 12]
 [20 21 22]
 [30 31 32]]
(3, 3)


### Distintas maneras de crear nd arrays

In [30]:
# 1. Crear array lleno de ceros.
ej1 = np.zeros((1080, 1920))
print(ej1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
# 2. Crear array lleno de un valor determinado.
ej2 = np.full((2, 2), 9.1)
print(ej2)

[[9.1 9.1]
 [9.1 9.1]]


In [36]:
# 3. Crear array de 2x2 con 1 en diagonal y el resto 0.
ej3 = np.eye(7, 7)
print(ej3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [39]:
# 4. Crear array de 10x2x7 (3 dimensiones) lleno de unos.
ej4 = np.ones((10, 2, 7))
print(ej4)

[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]


In [40]:
# 5. Crear array de floats aleatorios entre 0 y 1.
ej5 = np.random.random((5, 5))
print(ej5)

[[0.88795291 0.50881649 0.7992301  0.81872941 0.08111441]
 [0.27489748 0.72329582 0.13981929 0.42112817 0.01616997]
 [0.72720598 0.79042704 0.05775596 0.05604506 0.00192904]
 [0.99589912 0.60254712 0.05852375 0.01255554 0.90073828]
 [0.99601374 0.59643032 0.50319382 0.6754609  0.72261016]]


### Array de índices
A veces es útil preparar una serie de índices en un array para luego utilizarlos para operar sobre otro array.

In [42]:
# Creamos nuevo array.

arr_a = np.array(
    [[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]]
)
print(arr_a)
print(arr_a.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
(4, 3)


In [48]:
# Creamos 2 arrays con números enteros que usaremos como índices.

rows = np.arange(4)
cols = np.array([0, 1, 2, 0])

print(f'Elegimos estos índices para filas -> {rows}')
print(f'Elegimos estos índices para columnas -> {cols}')

Elegimos estos índices para filas -> [0 1 2 3]
Elegimos estos índices para columnas -> [0 1 2 0]


In [49]:
# Imprimimos los índices tomando uno de cada array de a pares.

for row, col, in zip(rows, cols):
    print(f'({row}, {col})')

(0, 0)
(1, 1)
(2, 2)
(3, 0)


In [54]:
# Seleccionamos un elemento de cada fila de la siguiente manera.

print(f'Valores contenidos en los índices: {arr_a[rows, cols]}')

Valores contenidos en los índices: [11 22 33 41]


In [55]:
# Operamos únicamente con los valores seleccionados.

print(arr_a)
arr_a[rows, cols] += 1000
print(arr_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


### Indexado Booleano
Indexado booleano para cambiar elementos.

In [57]:
# Creamos un array de 3x2.

arr_b = np.array([[11, 12], [21, 22], [31, 32]])
print(arr_b)
print(arr_b.shape)

[[11 12]
 [21 22]
 [31 32]]
(3, 2)


In [58]:
# Creamos un filtro.

filtro = (arr_b > 15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [59]:
# Aplicamos el filtro a nuestro array.

filtrado = arr_b[filtro]
print(filtrado)

[21 22 31 32]


In [64]:
# No es necesario crear primero el filtro y luego aplicarlo.
# Se puede hacer directamente de la siguiente manera.

print(arr_b[(arr_b > 15)])

# Otro filtro.

print(arr_b[(arr_b % 2 == 0)])

[21 22 31 32]
[12 22 32]


In [67]:
# El uso principal de este tipo de filtros es el de poder modificar
# los valores del array que cumplen cierto criterio.

arr_b[arr_b % 2 == 0] += 1000
print(arr_b)

[[  11 3012]
 [  21 3022]
 [  31 3032]]


### Slice en arrays de NumPy
Hacer Slice a un array sirve para aislar una sub-región de la matriz de un ndarray.

In [79]:
arr = np.array(
    [
        [11, 12, 13, 14, 15, 16],
        [21, 22, 23, 24, 25, 26],
        [31, 32, 33, 34, 35, 36],
        [41, 42, 43, 44, 45, 46]
    ]
)
print(arr)
print(arr.shape)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]
(4, 6)


In [89]:
# Creamos un slice de 2x2 a partir de arr.

slice = arr[:2, 1:3]
print(slice)
print(type(slice))

[[112  13]
 [ 22  23]]
<class 'numpy.ndarray'>


In [81]:
# Imprimimos el valor fila 0 columna 0 del slice.

print(f'Slice: {slice[0, 0]}')

Slice: 12


In [82]:
# Ahora sumaremos 100 al valor de la posición (0, 0) del slice.

slice[0, 0] += 100
print(f'Slice: {slice[0, 0]}')

Slice: 112


In [86]:
# Ahora imprimimos la posición (0, 1) del array original.

print(arr[0, 1])

112


In [90]:
# De este modo confirmamos que un slice no es un nuevo array, sino
# un puntero o  acceso directo al array original. Si modificamos algún
# dato de un slice estaremos modificándolo en el array original.

print(arr)
print(type(arr))

[[ 11 112  13  14  15  16]
 [ 21  22  23  24  25  26]
 [ 31  32  33  34  35  36]
 [ 41  42  43  44  45  46]]
<class 'numpy.ndarray'>


In [92]:
# Para obtener un nuevo array a partir de un slice.

nuevo_arr = np.array(slice)
print(nuevo_arr)

[[112  13]
 [ 22  23]]


### Tipos de datos de los arrays NumPy

In [93]:
# En estos dos casos Python se encarga de asignar el tipo de dato.

ej1 = np.array([11, 12])
print(ej1.dtype)

int64


In [94]:
ej2 = np.array([11.0, 12.0])
print(ej2.dtype)

float64


In [97]:
# Podemos forzar el tipo de dato indicándolo de manera explícita.

ej3 = np.array([11, 12], dtype=np.float64)
print(ej3.dtype)

float64


In [99]:
ej4 = np.array([11.1, 12.7], dtype=np.int64)
print(ej4.dtype)
print(ej4)

int64
[11 12]


### Operaciones aritméticas

In [107]:
x = np.array([[111, 112], [121, 122]], dtype=np.int64)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [108]:
# Resta.

print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [109]:
# Multiplicación.

print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [110]:
# División.

print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [111]:
# Raíz cuadrada.

print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


### Operaciones estadísticas básicas

In [117]:
# Generar un array aleatorio.

arr = 10 * np.random.randn(2, 5)
print(arr)

[[ 19.62303908  -5.74166852  -0.86986327   9.02906613  12.82559367]
 [-13.29708677  -5.01951571  12.24339825  20.35663691  -7.0678362 ]]


In [118]:
# Calcular la media (promedio) de un array.

print(arr.mean())

4.208176355470423


In [121]:
# Calcular el promedio de cada fila individualmente.
# eje o axis 0 = columnas
# eje o axis 1 = filas

print(arr.mean(axis=0))
print(arr.mean(axis=1))

[ 3.16297616 -5.38059212  5.68676749 14.69285152  2.87887874]
[6.97323341 1.4431193 ]


In [123]:
# Creamos un array de 10 elementos aleatorios.

desordenado = np.random.randn(10)
print(desordenado)

[ 1.92308192  1.66511716 -1.8575921  -0.68829758  0.11909677 -0.54397606
 -1.20169524 -1.66072445 -1.88674776 -0.88400598]


In [126]:
# Creamos una copia.

ordenado = np.array(desordenado)
ordenado.sort()

print(ordenado)

[-1.88674776 -1.8575921  -1.66072445 -1.20169524 -0.88400598 -0.68829758
 -0.54397606  0.11909677  1.66511716  1.92308192]


In [127]:
# Buscar elementos únicos (MUY ÚTIL!).

arr = np.array([1, 2, 1, 4, 2, 1, 4, 2])
print(np.unique(arr))


[1 2 4]


In [129]:
# Operaciones de conjunto.

s1 = np.array(['perro', 'gato', 'canario'])
s2 = np.array(['perro', 'gato', 'hurón'])
print(s1)
print(s2)

['perro' 'gato' 'canario']
['perro' 'gato' 'hurón']


In [130]:
# Intersección.

print(np.intersect1d(s1, s2))

['gato' 'perro']


In [131]:
# Unión.

print(np.union1d(s1, s2))

['canario' 'gato' 'hurón' 'perro']


In [132]:
# Elementos de s1 que no están en s2.

print(np.setdiff1d(s1, s2))

['canario']


In [133]:
# Elementos de s1 que sí están en s2.

print(np.in1d(s1, s2))

[ True  True False]


### Algunas operaciones frecuentes

In [137]:
# Sumar todos los elementos de un array.

ex1 = np.array([[11, 12], [21, 22]])
print(ex1)
print()
print(np.sum(ex1))

[[11 12]
 [21 22]]

66


In [138]:
# Sumar solo los elementos de una columna.

print(np.sum(ex1, axis=0))

[32 34]


In [139]:
# Sumar solo los elementos de una fila.

print(np.sum(ex1, axis=1))

[23 43]


In [142]:
# Reformateando un array (IMPORTANTE).

# Creamos un array.
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [143]:
# Cambiamos su forma.

reshaped_arr = arr.reshape(4, 5)
print(reshaped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [147]:
# Transponer o transposicionar un array.

ex1 = np.array([[11, 12], [21, 22]])
print(ex1)
print()
print(ex1.T)

[[11 12]
 [21 22]]

[[11 21]
 [12 22]]


In [149]:
# WHERE ... NUY ÚTIL!

mat = np.random.rand(4, 4)
print(mat)

[[0.65484635 0.94511282 0.87775092 0.39507371]
 [0.65666202 0.14507779 0.51809283 0.99177284]
 [0.84953341 0.39580613 0.21493355 0.37629672]
 [0.02368954 0.49901455 0.41723267 0.6943742 ]]


In [154]:
# Ahora le paso como argumentos una condición, valor si True y valor si False.
# Por ejemplo:
#   Si se cumple que el valor es > 0.5, cambia el valor por 1000, y si no por -1.

print(np.where(mat > 0.5, 1000, -1))

[[1000 1000 1000   -1]
 [1000   -1 1000 1000]
 [1000   -1   -1   -1]
 [  -1   -1   -1 1000]]


In [155]:
# Comprobar si algún elemento del array es True. Nótese que funciona tanto con valores
# booleanos (True y False) como con números, ya que 0 se considera False y todo distinto
# de 0 True.

arr_bools = np.array([0, 0, 0, 0, 0, True])
print(arr_bools.any())

True


In [156]:
# Comprobar si todos los elementos del array son True. Al igual que antes, funciona tanto
# con valores booleanos (True y False) como con números, ya que 0 se considera False y
# todo distinto de 0 True.

arr_bools = np.array([1, 1, False])
print(arr_bools.all())

False


### Uniendo data sets

In [158]:
# Creamos dos array de 2x2 con números aleatorios tal que el mínimo sea 2 y el máximo 50.
K = np.random.randint(low=2, high=50, size=(2, 2))
print(K)

print()

M = np.random.randint(low=2, high=50, size=(2, 2))
print(M)

[[10  2]
 [29  2]]

[[46 16]
 [45  4]]


In [159]:
# Unimos apilando verticalmente.

print(np.vstack((K, M)))

[[10  2]
 [29  2]
 [46 16]
 [45  4]]


In [160]:
# Unimos apilando horizontalmente.

print(np.hstack((K, M)))

[[10  2 46 16]
 [29  2 45  4]]


In [163]:
# Otra opción es unirlos concatenándolos.

print(np.concatenate([K, M], axis=0))
print()
print(np.concatenate([K, M], axis=1))

[[10  2]
 [29  2]
 [46 16]
 [45  4]]

[[10  2 46 16]
 [29  2 45  4]]


### Propagación

In [164]:
# Creamos un array de 4x4 con ceros.

base = np.zeros((4, 4))
print(base)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [165]:
# Creamos un array unidimensional llamado row con el mimso número de elementos que la base.

row = np.array([1, 0, 2, 7])
print(row)
print(row.shape)

[1 0 2 7]
(4,)


In [166]:
# Vamos a realizar una suma de los 4 elementos de row a cada fila de base (propagación).

y = base + row
print(y)

[[1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]]


In [168]:
# Repetimos lo mismo pero en este caso la propagación de la suma es por columnas.

col = np.array([[0, 1, 2, 3]])
print(col)

[[0 1 2 3]]


In [169]:
# Ahora transponemos (verticalizamos) este array.

col = col.T
print(col)

[[0]
 [1]
 [2]
 [3]]


In [170]:
# Realizamos la propagación vertical.

y = base + col
print(y)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [171]:
# Probemos a crear una columna que no tiene el mismo alto que nuestras columnas de base.

col = np.array([[0, 1, 2]])
col = col.T
print(col)

[[0]
 [1]
 [2]]


In [172]:
# Veamos qué pasa si quiero hacer una propagación vertical como antes.

y = base + col
print(y)

ValueError: operands could not be broadcast together with shapes (4,4) (3,1) 

In [173]:
# El ejemplo anterior no ha funcionado, como era de esperar.

In [174]:
# Probemos a propagar un array de un solo elemento por toda la base.

arr = np.array([1])
print(arr)
print()
print(base + arr)

[1]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Prueba de velocidad

In [178]:
from numpy import arange
from timeit import Timer

In [181]:
# Creamo un array de una dimensión de 1000000 elementos.

size = 1000000
timeits = 1000

nd_array = arange(size)
print(f'Tipo de dato: {type(nd_array)}')
print(f'Forma: {nd_array.shape}')

Tipo de dato: <class 'numpy.ndarray'>
Forma: (1000000,)


In [184]:
# Con la función Timer podemos medir el tiempo que lleva realizar
# una operación o función.

timer_numpy = Timer('nd_array.sum()', 'from __main__ import nd_array')
print(f'Time taken by numpy ndarray: {timer_numpy.timeit(timeits)} seconds.')

Time taken by numpy ndarray: 0.6119546050322242 seconds.


In [185]:
a_list = list(range(size))
print(type(a_list))
print(f'Forma: {len(a_list)}')

<class 'list'>
Forma: 1000000


In [186]:
timer_list = Timer('sum(a_list)', 'from __main__ import a_list')
print(f'Time taken by list: {timer_list.timeit(timeits)} seconds.')

Time taken by list: 6.520576351962518 seconds.


### Grabar array a disco / Recuperar array de disco

In [187]:
x = np.array([23.23, 24.24])

In [188]:
np.save('array_importante', x)

In [189]:
!ls -lrt

total 84
-rw-rw-r-- 1 jdg jdg    74 may  9 12:09 README.md
-rw-rw-r-- 1 jdg jdg 35149 may  9 12:09 LICENSE
-rw-rw-r-- 1 jdg jdg 38928 may 10 19:15 NumPy.ipynb
-rw-rw-r-- 1 jdg jdg   144 may 10 19:15 array_importante.npy


In [190]:
recuperado = np.load('array_importante.npy')
print(f'El array recuperado es: {recuperado}')

El array recuperado es: [23.23 24.24]
